#!/bin/bash

# See also encryptFile

# Encryption
ENCKEY=''
DIGEST='sha256'
CIPHER='aes-256-cbc'

# pv
BLOCKSIZE=16

if [ $# -lt 2 ]; then
	echo -e "Decrypt a file.\n" >&2
	echo -e "Usage: $(basename "$0") <input> <output>\n" >&2
	echo -e "If <output> is - then output is redirected to STDOUT\n" >&2
	exit 1
fi

if [ ! -e "$1" ]; then # -f does not catch FIFOs
	echo -e "Error: File '$1' not found.\n" >&2
	exit 1
fi

checkBinarys() {
	#http://stackoverflow.com/a/677212/568737
	BINS=("$@")
	for BIN in "${BINS[@]}"; do
		hash $BIN 2>/dev/null || {
			echo -e "Error: Binary '$BIN' is missing.\n" >&2
			exit 1
		}
	done
}

# Check if all needed binarys are present
checkBinarys "openssl" "pv"

if [ ! $ENCKEY ]; then
	read -s -p "Enter password: " ENCKEY
	[ ! $ENCKEY ] && exit 1
fi

if [ "$2" == "-" ]; then
	# STDOUT
	if [ ! -p "$1" ]; then
		# no FIFO
		# Encrypt & Upload
		openssl "$CIPHER" -d -salt -md "$DIGEST" -k "$ENCKEY" -in "$1" |
		pv -bper -s $(( ($(stat -c%s "$1") + $BLOCKSIZE) / $BLOCKSIZE * $BLOCKSIZE + $BLOCKSIZE)) 
	else
		# FIFO
		openssl "$CIPHER" -d -salt -md "$DIGEST" -k "$ENCKEY" -in "$1" |
		pv -bper
	fi
else
	# OUTPUT to FILE
	echo "Decrypting: $1 --> $2"
	if [ ! -p "$1" ]; then
		# no FIFO
		# Encrypt & Upload
		openssl "$CIPHER" -d -salt -md "$DIGEST" -k "$ENCKEY" -in "$1" |
		pv -bper -s $(( ($(stat -c%s "$1") + $BLOCKSIZE) / $BLOCKSIZE * $BLOCKSIZE + $BLOCKSIZE)) > "$2"
	else
		# FIFO
		openssl "$CIPHER" -d -salt -md "$DIGEST" -k "$ENCKEY" -in "$1" |
		pv -bper > "$2"
	fi
fi
